CREATE TABLE IF NOT EXISTS signal_table_15min (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid VARCHAR(32) NOT NULL,
    asset_1 VARCHAR(32) NOT NULL,
    asset_2 VARCHAR(32) NOT NULL,
    tp DOUBLE NOT NULL,
    sl DOUBLE NOT NULL,
    rolling_window_15m INT NOT NULL,
    open_threshold_multiplier DOUBLE NOT NULL,
    entry_z_threshold DOUBLE NOT NULL,
    zscore_sl_threshold DOUBLE NOT NULL DEFAULT 6,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    last_update_ts DATETIME(6) NOT NULL,
    last_z_score FLOAT NULL,
    max_z_score FLOAT NULL,
    min_z_score FLOAT NULL,
    asset1_5m_vol FLOAT NULL,
    asset1_1h_vol FLOAT NULL,
    asset2_5m_vol FLOAT NULL,
    asset2_1h_vol FLOAT NULL,
    signal_this_month INT NOT NULL DEFAULT 0,
    signal_prev_month INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uq_signal_15min_uuid (uuid),
    KEY ix_signal_15min_asset1 (asset_1),
    KEY ix_signal_15min_updated (last_update_ts),
    KEY ix_signal_15min_enabled (enabled)
);

CREATE TABLE IF NOT EXISTS pair_state_15min (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid VARCHAR(32) NOT NULL,
    adf FLOAT NULL,
    p_value FLOAT NULL,
    hurst FLOAT NULL,
    hl FLOAT NULL,
    hl_timeframe_minutes SMALLINT UNSIGNED NOT NULL DEFAULT 60,
    spread_skew FLOAT NULL,
    spread_kurt FLOAT NULL,
    beta FLOAT NULL,
    beta_norm FLOAT NULL,
    hl_spread_med FLOAT NULL,
    last_spread FLOAT NULL,
    win_rate_180 FLOAT NULL,
    rew_risk_180 FLOAT NULL,
    num_trades_180 INT NULL,
    total_pnl_180 FLOAT NULL,
    expect_180 FLOAT NULL,
    level_180 ENUM('level_0','level_1','level_2','quarantine')
        NOT NULL DEFAULT 'level_0',
    win_rate_30 FLOAT NULL,
    rew_risk_30 FLOAT NULL,
    num_trades_30 INT NULL,
    total_pnl_30 FLOAT NULL,
    expect_30 FLOAT NULL,
    level_30 ENUM('level_0','level_1','level_2','quarantine')
        NOT NULL DEFAULT 'level_0',
    quarantine_until DATETIME(6) NULL,
    quarantine_reason VARCHAR(32) NULL,
    activity_score FLOAT NULL,
    last_update_ts DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_pair_state_15min_uuid (uuid),
    KEY ix_pair_state_15min_level180 (level_180),
    KEY ix_pair_state_15min_level30 (level_30),
    KEY ix_pair_state_15min_quarantine (quarantine_until),
    KEY ix_pair_state_15min_updated (last_update_ts)
);

CREATE TABLE IF NOT EXISTS trade_res_15min (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid VARCHAR(32) NOT NULL,
    open_dt DATETIME(6) NOT NULL,
    close_dt DATETIME(6) NULL,
    pnl FLOAT NULL,
    closed_by VARCHAR(40) NULL,
    bot_id VARCHAR(20) NOT NULL,
    open_cond VARCHAR(255) NULL,
    close_cond VARCHAR(255) NULL,
    pos_val FLOAT NULL,
    pnl_pers FLOAT NULL,
    PRIMARY KEY (id),
    KEY ix_trade_res_15min_uuid (uuid),
    KEY ix_trade_res_15min_open (open_dt),
    KEY ix_trade_res_15min_close (close_dt),
    KEY ix_trade_res_15min_bot (bot_id)
);

CREATE TABLE IF NOT EXISTS asset_locks_15min (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    bot_id VARCHAR(20) NOT NULL,
    asset VARCHAR(32) NOT NULL,
    uuid VARCHAR(32) NOT NULL,
    created_ts DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_asset_locks_15min_asset (asset),
    KEY ix_asset_locks_15min_bot (bot_id),
    KEY ix_asset_locks_15min_uuid (uuid)
);
